sudo: required
services:
    - docker

before_install:
    - docker build -t kissta/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kissta/react-test npm test

after_success:
    - docker build -t kissta/multi-client ./client
    - docker build -t kissta/multi-nginx ./nginx
    - docker build -t kissta/multi-server ./server
    - docker build -t kissta/multi-worker ./worker 
    #log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to dockerhub
    - docker push kissta/multi-client
    - docker push kissta/multi-nginx
    - docker push kissta/multi-server
    - docker push kissta/multi-worker